### ISSUE TITLE
Add Spring Boot Infrastructure

### ISSUE THREAD

**Issue by majagabajaga** [mironuk/CarServiceWeb#3]
Implement initial spring boot infrastructure (project skeleton). This should include:

- Application launcher
- JPA integration
- Thymeleaf integration

**Comment by majagabajaga** [comment]
Created pull request: https://github.com/mironuk/CarServiceWeb/pull/2

**Comment by mironuk** [comment]
I think this issue can be closed. :)

**Comment by majagabajaga** [comment]
Closed.
